# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2cf75b6c0419fc82bc5864ce144c8d32"
name = "Stych.ai"
application_url = "https://epson-draw-blackjack-definition.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sasban.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://epson-draw-blackjack-definition.trycloudflare.com/auth/callback",
  "https://epson-draw-blackjack-definition.trycloudflare.com/auth/shopify/callback",
  "https://epson-draw-blackjack-definition.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
